"""cria etapas das competencias

Revision ID: 6fa01b86eec9
Revises: cee861d227c0
Create Date: 2026-07-15 00:00:04.933313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa01b86eec9'
down_revision: Union[str, Sequence[str], None] = 'cee861d227c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competence_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.String(length=30), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('numero_sei_documento', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordem > 0', name='ck_competence_step_positive_order'),
    sa.ForeignKeyConstraint(['competence_id'], ['competences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsavel_id'], ['people.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competence_id', 'codigo', name='uq_competence_step_code')
    )
    op.create_index(op.f('ix_competence_steps_codigo'), 'competence_steps', ['codigo'], unique=False)
    op.create_index(op.f('ix_competence_steps_competence_id'), 'competence_steps', ['competence_id'], unique=False)
    op.create_index(op.f('ix_competence_steps_responsavel_id'), 'competence_steps', ['responsavel_id'], unique=False)
    op.create_index(op.f('ix_competence_steps_situacao'), 'competence_steps', ['situacao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competence_steps_situacao'), table_name='competence_steps')
    op.drop_index(op.f('ix_competence_steps_responsavel_id'), table_name='competence_steps')
    op.drop_index(op.f('ix_competence_steps_competence_id'), table_name='competence_steps')
    op.drop_index(op.f('ix_competence_steps_codigo'), table_name='competence_steps')
    op.drop_table('competence_steps')
    # ### end Alembic commands ###
