"""cria tabelas iniciais do modulo contratos

Revision ID: 7039730c73c8
Revises: 
Create Date: 2026-07-14 22:54:54.443609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7039730c73c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=255), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('representante_legal', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cnpj'), 'companies', ['cnpj'], unique=True)
    op.create_index(op.f('ix_companies_razao_social'), 'companies', ['razao_social'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('siape', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('tipo_vinculo', sa.String(length=40), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_email'), 'people', ['email'], unique=True)
    op.create_index(op.f('ix_people_nome'), 'people', ['nome'], unique=False)
    op.create_index(op.f('ix_people_siape'), 'people', ['siape'], unique=True)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('processo_sei_contratacao', sa.String(length=30), nullable=False),
    sa.Column('processo_sei_fiscalizacao', sa.String(length=30), nullable=True),
    sa.Column('processo_sei_pagamento', sa.String(length=30), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=False),
    sa.Column('valor_global', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_mensal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('situacao', sa.String(length=30), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_company_id'), 'contracts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contracts_data_fim'), 'contracts', ['data_fim'], unique=False)
    op.create_index(op.f('ix_contracts_numero'), 'contracts', ['numero'], unique=False)
    op.create_index(op.f('ix_contracts_processo_sei_contratacao'), 'contracts', ['processo_sei_contratacao'], unique=False)
    op.create_index(op.f('ix_contracts_processo_sei_fiscalizacao'), 'contracts', ['processo_sei_fiscalizacao'], unique=False)
    op.create_index(op.f('ix_contracts_processo_sei_pagamento'), 'contracts', ['processo_sei_pagamento'], unique=False)
    op.create_index(op.f('ix_contracts_situacao'), 'contracts', ['situacao'], unique=False)
    op.create_table('contract_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('titular', sa.Boolean(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('documento_designacao', sa.String(length=100), nullable=True),
    sa.Column('numero_sei_documento', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'person_id', 'role', 'data_inicio', name='uq_contract_assignment')
    )
    op.create_index(op.f('ix_contract_assignments_contract_id'), 'contract_assignments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_assignments_person_id'), 'contract_assignments', ['person_id'], unique=False)
    op.create_index(op.f('ix_contract_assignments_role'), 'contract_assignments', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_assignments_role'), table_name='contract_assignments')
    op.drop_index(op.f('ix_contract_assignments_person_id'), table_name='contract_assignments')
    op.drop_index(op.f('ix_contract_assignments_contract_id'), table_name='contract_assignments')
    op.drop_table('contract_assignments')
    op.drop_index(op.f('ix_contracts_situacao'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_processo_sei_pagamento'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_processo_sei_fiscalizacao'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_processo_sei_contratacao'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_numero'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_data_fim'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_company_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_people_siape'), table_name='people')
    op.drop_index(op.f('ix_people_nome'), table_name='people')
    op.drop_index(op.f('ix_people_email'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_companies_razao_social'), table_name='companies')
    op.drop_index(op.f('ix_companies_cnpj'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
