"""cria tabela de competencias

Revision ID: cee861d227c0
Revises: 7039730c73c8
Create Date: 2026-07-14 23:48:33.846564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee861d227c0'
down_revision: Union[str, Sequence[str], None] = '7039730c73c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('valor_previsto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_faturado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ano >= 2000 AND ano <= 2100', name='ck_competence_valid_year'),
    sa.CheckConstraint('mes >= 1 AND mes <= 12', name='ck_competence_valid_month'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'ano', 'mes', name='uq_competence_contract_year_month')
    )
    op.create_index(op.f('ix_competences_ano'), 'competences', ['ano'], unique=False)
    op.create_index(op.f('ix_competences_contract_id'), 'competences', ['contract_id'], unique=False)
    op.create_index(op.f('ix_competences_mes'), 'competences', ['mes'], unique=False)
    op.create_index(op.f('ix_competences_situacao'), 'competences', ['situacao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competences_situacao'), table_name='competences')
    op.drop_index(op.f('ix_competences_mes'), table_name='competences')
    op.drop_index(op.f('ix_competences_contract_id'), table_name='competences')
    op.drop_index(op.f('ix_competences_ano'), table_name='competences')
    op.drop_table('competences')
    # ### end Alembic commands ###
